
class WorkflowDefaults(object):

    WORKFLOW_DEFAULT_PRIORITY_SCALING_FACTOR = 10.0

    WORKFLOW_LOW_PRIORITY_SCALING_FACTOR = 0.0

    WORKFLOW_NORMAL_PRIORITY_SCALING_FACTOR = 10.0

    WORKFLOW_HIGH_PRIORITY_SCALING_FACTOR = 18.0

    WORKFLOW_CRITICAL_PRIORITY_SCALING_FACTOR = 32.0
